# Name the node stage "ApplicationBuilder"
FROM node:16 AS ApplicationBuilder
# Set working directory
WORKDIR /app
# Copy all files from current directory to working dir in image
COPY . .
# install node modules and build the web-app
RUN yarn install && yarn build

# nginx to serve the webpage
FROM nginx:alpine
# Set working directory to nginx asset directory
WORKDIR /usr/share/nginx/html
# Remove default nginx static assets
RUN rm -rf ./*
# Copy static assets from ApplicationBuilder stage
COPY --from=ApplicationBuilder /app/dist .
# Containers shall run with global directives along with the daemon turned off
ENTRYPOINT ["nginx", "-g", "daemon off;"]